PL/Controllers/EmpresaController.cs
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class EmpresaController : Controller
    {
        private readonly IConfiguration _configuration;

        private readonly Microsoft.AspNetCore.Hosting.IHostingEnvironment _hostingEnvironment;

        public EmpresaController(IConfiguration configuration, Microsoft.AspNetCore.Hosting.IHostingEnvironment hostingEnvironment)
        {
            _configuration = configuration;
            _hostingEnvironment = hostingEnvironment;
        }
        // GET: Empresa
        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Empresa empresa = new ML.Empresa();
            //ML.Result result = BL.Empresa.GetAllEF(empresa);
            ML.Result result = new ML.Result();
            result.Objects = new List<object>();
            try
            {
                string urlAPI = _configuration["UrlAPI"];

                using (var user = new HttpClient())
                {
                    user.BaseAddress = new Uri(urlAPI);

                    var responseTask = user.GetAsync("Empresa/GetAll");
                    //result = BL.Usuario.GetAllEF();

                    responseTask.Wait();

                    var resultServicio = responseTask.Result;

                    if (resultServicio.IsSuccessStatusCode)
                    {
                        var readTask = resultServicio.Content.ReadAsAsync<ML.Result>();
                        readTask.Wait();

                        foreach (var resultItem in readTask.Result.Objects)
                        {
                            ML.Empresa resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Empresa>(resultItem.ToString());
                            result.Objects.Add(resultItemList);
                        }

                        result.Correct = true;
                    }
                }
            }
            catch (Exception ex)
            {
                result.Correct = false;
                result.Message = ex.Message;
            }
            if (result.Correct)
            {
                empresa.Empresas = result.Objects;
            }
            else
            {
                ViewBag.Message = "Ocurrio un error al realizar la consulta";
            }
            return View(empresa);
        }

        [HttpPost]
        public ActionResult GetAll(ML.Empresa empresa)
        {
            ML.Result result = BL.Empresa.GetAllEF(empresa);
            if (result.Correct)
            {
                empresa.Empresas = result.Objects;
            }
            else
            {
                ViewBag.Message = "Ocurrio un error al realizar la consulta";
            }
            return View(empresa);
        }

        [HttpGet]
        public ActionResult Form(int? IdEmpresa)
        {
            ML.Empresa empresa = new ML.Empresa();
            if (IdEmpresa == null)
            {
                return View(empresa);
            }
            else
            {
                ML.Result result = BL.Empresa.GetByIdEF(IdEmpresa.Value);
                if (result.Correct)
                {
                    empresa = (ML.Empresa)result.Objeto;
                }
                else
                {
                    ViewBag.Message = "Ocurrio un error al buscar el usuario";
                }
                return View(empresa);
            }
        }

        [HttpPost]
        public ActionResult Form(ML.Empresa empresa)
        {
            IFormFile image = Request.Form.Files["FileImage"];
            if (image != null)
            {
                byte[] ImagenBytes = ConvertToBytes(image);
                empresa.Logo = Convert.ToBase64String(ImagenBytes);
            }
            //HttpPostedFileBase file = Request.Files["ImagenData"];

            //if (file.ContentLength > 0)
            //{
            //    empresa.Logo = ConvertToBytes(file);
            //}
            //ADD
            if (empresa.IdEmpresa == 0)
            {
                ML.Result result = BL.Empresa.AddEF(empresa);
                if (result.Correct)
                {
                    ViewBag.Message = result.Message;
                }
                else
                {
                    ViewBag.Message = "Error: " + result.Message;
                }
            }
            else
            {
                //UPDATE
                if (empresa != null)
                {
                    ML.Result result = BL.Empresa.UpdateEF(empresa);
                    if (result.Correct)
                    {
                        ViewBag.Message = result.Message;
                    }
                    else
                    {
                        ViewBag.Message = "Error: " + result.Message;
                    }
                }
            }
            return PartialView("Modal");
        }

        //[HttpDelete]
        public ActionResult Delete(int idEmpresa)
        {
            ML.Empresa empresa = new ML.Empresa();
            if (empresa != null)
            {
                ML.Result result = BL.Empresa.DeleteEF(idEmpresa);
                if (result.Correct)
                {
                    ViewBag.Message = result.Message;
                }
                else
                {
                    ViewBag.Message = "Error: " + result.Message;
                }
            }
            else
            {
                return Redirect("/Empresa/GetAll");
            }
            return PartialView("Modal");
        }

        public static byte[] ConvertToBytes(IFormFile logo)
        {

            using var fileStream = logo.OpenReadStream();

            byte[] bytes = new byte[fileStream.Length];
            fileStream.Read(bytes, 0, (int)fileStream.Length);

            return bytes;
        }
        //public byte[] ConvertToBytes(HttpPostedFileBase logo)
        //{
        //    byte[] data = null;
        //    System.IO.BinaryReader reader = new System.IO.BinaryReader(logo.InputStream);
        //    data = reader.ReadBytes((int)logo.ContentLength);
        //    return data;
        //}
    }
}

PL/Views/Empresa/Form.cshtml
@model ML.Empresa
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <h2>Form</h2>
    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("Form", "Empresa", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <h3 class="text-center">Datos de la empresa</h3>
                <div class="form-horizontal">

                    <div class="form-group">

                        <div class="col-md-3">

                            @Html.HiddenFor(model => model.IdEmpresa)

                            @*@Html.TextBoxFor(model => model.IdUsuario, new { @class = "hidden form-control" })

                             @Html.ValidationMessageFor(model => model.IdUsuario)*@
                        </div>
                    </div>

                    <div class="container">
                        <div class="row">
                            <div class="col">

                                <div class="form-group">
                                    
                                    @Html.LabelFor(model => model.Nombre)

                                    @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @id = "txtNombre" })

                                    @Html.ValidationMessageFor(model => model.Nombre)

                                </div>

                                <div class="form-group">

                                    @Html.LabelFor(model => model.Telefono)

                                    @Html.TextBoxFor(model => model.Telefono, new { @class = "form-control" })

                                    @Html.ValidationMessageFor(model => model.Telefono)

                                </div>

                            </div>

                            <div class="col">

                                <div class="form-group">

                                    @Html.LabelFor(model => model.Email)

                                    @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })

                                    @Html.ValidationMessageFor(model => model.Email)

                                </div>

                                <div class="form-group">

                                    @Html.LabelFor(model => model.DireccionWeb)

                                    @Html.TextBoxFor(model => model.DireccionWeb, new { @class = "form-control" })

                                    @Html.ValidationMessageFor(model => model.DireccionWeb)

                                </div>

                            </div>

                            <div class="col">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Logo)
                                    <input type="file" accept=".png, .jpg, .jpeg" , id="inputImage" name="FileImage" onchange="readImage(this)" />
                                    @if (Model.Logo != null)
                                    {
                                        var imagenSRC = $"data:image;base64,{Model.Logo}";
                                        <img id="ImagenPreview" src='@imagenSRC' class="rounded img-thumbnail" alt='Category Image' height='200px' width='200px'>
                                    }
                                    else
                                    {
                                        <img id="ImagenPreview" src="~/Image/sinlogo.jpg" class="rounded img-thumbnail" alt='Category Image' height='200px' width='200px' required>
                                    }
                                </div>
                                @Html.HiddenFor(model => model.Logo)
                            </div>
                        </div>
                    </div>

                    <div class="container">
                        <div class="row justify-content-md-center">
                            <div class="col col-lg-2">
                                <input type="submit" value="Guardar" class="btn btn-success" />

                                @Html.ActionLink("Regresar", "GetAll", "Empresa", htmlAttributes: new { @class = "btn btn-danger" })
                            </div>
                        </div>
                    </div>

                </div>
            }
        </div>
    </div>
</div>

@section Scripts{

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script type="text/javascript">
        function readImage(imagen) {
            var fileName = imagen.value;
            var idxDot = fileName.lastIndexOf(".") + 1;
            var extFile = fileName.substr(idxDot, fileName.length).toLowerCase();

            if (extFile == "jpg" || extFile == "jpeg" || extFile == "png") {

                if (imagen.files && imagen.files[0]) {
                    var reader = new FileReader();
                    reader.onload = (e) => {
                        $("#ImagenPreview").attr("src", e.target.result);
                    };
                    reader.readAsDataURL(imagen.files[0]);
                }

            } else {

                alert("This is not an allowed file type. \nOnly jpg / jpeg and png files are allowed!.");

                $('#inputImage').val(null);

                $("#ImagenPreview").attr("src", "~/Image/sinlogo.jpg");

            }

        }
    </script>
}

PL/Views/Empresa/GetAll.cshtml
@model ML.Empresa
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h2>Lista de empresas</h2>
    <p>Aqui puede ver, editar o agregar a una empresa</p>
    <p>Para agregar una empresa presione el boton verde</p>
    <p>Para editar una empresa presione el boton azul</p>
    <p>Para eliminar una empresa presione el boton rojo</p>
    <p>Para buscar un usuario presione el boton amarillo</p>
    <hr />

    <div class="row">
        <div style="float:right">
            @Html.ActionLink("+", "Form", "Empresa", htmlAttributes: new { @class = "btn btn-success" })
        </div>
    </div>

    @using (Html.BeginForm("GetAll", "Empresa", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="container mt-5">
            <div class="row">
                <h5>Buscar Empresa</h5>
                <div class="col-md-3">
                    <div class="form-group">

                        @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @placeholder = "Nombre" })

                    </div>
                </div>

                <div class="col-md-3">
                    <div class="container">
                        <div class="row justify-content-md-center">
                            <div class="col col-lg-2">
                                <input type="submit" value="Buscar" class="btn btn-warning" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }

    <div class="row mt-5">
        <table class="table table-responsive" id="tblEmpresa">
            <thead class="table-dark">
                <tr>
                    <th>
                        IdEmpresa
                    </th>
                    <th>
                        Nombre
                    </th>
                    <th>
                        Telefono
                    </th>
                    <th>
                        Email
                    </th>
                    <th>
                        DireccionWeb
                    </th>
                    <th>
                        Imagen
                    </th>
                    <th>
                        Editar
                    </th>
                    <th>
                        Eliminar
                    </th>
                </tr>
            </thead>
            <tbody class="table-info">
                @foreach (ML.Empresa empresa in Model.Empresas)
                {
                        <tr>
                            <td>
                            @empresa.IdEmpresa
                            </td>
                            <td>
                            @empresa.Nombre
                            </td>
                            <td>
                            @empresa.Telefono
                            </td>
                            <td>
                            @empresa.Email
                            </td>
                            <td>
                            @empresa.DireccionWeb
                            </td>
                            <td>
                            @if (empresa.Logo != null)
                            {
                                var imagenSRC = $"data:image;base64,{empresa.Logo}";
                                <img src='@imagenSRC' height='150px' width='150px'>
                            }
                            else
                            {
                                <img src="~/Image/sinlogo.jpg" height='150px' width='150px'/>
                            }
                            </td>
                            <td class="text-center">
                            <a class="btn btn-primary bi-pencil-square" href="@Url.Action("Form", "Empresa", new { IdEmpresa = empresa.IdEmpresa })"></a>
                            </td>
                            <td class="text-center">
                            <a class="btn btn-danger bi-trash" href="@Url.Action("Delete", "Empresa", new { IdEmpresa = empresa.IdEmpresa })" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"></a>
                            </td>
                        </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@section Scripts
    {

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/dataTables.material.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap5.min.js"></script>

    <script>
        $(document).ready(function () {
            $('#tblEmpresa').DataTable({
                searching: false,
                "lengthMenu": [[5, 10, 15, 20, -1], [5, 10, 15, 20, "All"]],
                autoWidth: false,
                columnDefs: [
                    {
                        targets: ['_all'],
                        className: 'mdc-data-table__cell',
                    },
                ],
                language: {
                    url: "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json",
                },
            });
        });
    </script>

}

PL/Views/Empresa/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">

                @Html.ActionLink("Regresar", "GetAll", "Empresa", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>