PL/Controllers/EmpleadoDependienteController.cs
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class EmpleadoDependienteController : Controller
    {
        [HttpGet]
        public IActionResult GetAll()
        {
            ML.Empleado empleado = new ML.Empleado();
            ML.Result result = BL.Empleado.GetAll();
            if (result.Correct)
            {
                empleado.Empleados = result.Objects;
            }
            else
            {
                ViewBag.Message = "Ocurrio un error al realizar la consulta";
            }
            return View(empleado);
        }

        [HttpGet]
        public IActionResult GetAllDp(string? NumeroEmpleado)
        {
            ML.Dependiente dependiente = new ML.Dependiente();
            ML.Result result = BL.Dependiente.GetByIdEmpleado(NumeroEmpleado);
            if (result.Correct)
            {
                dependiente.Dependientes = result.Objects;
            }
            else
            {
                ViewBag.Message = "Ocurrio un error al realizar la consulta";
            }
            return View(dependiente);
        }

        [HttpGet]
        public ActionResult Form(int? idDependiente)
        {
            ML.Result resultEmpleado = BL.Empleado.GetAll();
            ML.Result resultDependienteTipo = BL.DependienteTipo.GetAll();

            ML.Dependiente dependiente = new ML.Dependiente();
            dependiente.Empleado = new ML.Empleado();
            dependiente.DependienteTipo = new ML.DependienteTipo();

            if (idDependiente == null)
            {
                dependiente.Empleado.Empleados = resultEmpleado.Objects;
                dependiente.DependienteTipo.DependienteTipos = resultDependienteTipo.Objects;
                return View(dependiente);
            }
            else
            {
                ML.Result result = BL.Dependiente.GetById(idDependiente.Value);
                if (result.Correct)
                {
                    dependiente = (ML.Dependiente)result.Objeto;
                    dependiente.Empleado.Empleados = resultEmpleado.Objects;
                    dependiente.DependienteTipo.DependienteTipos = resultDependienteTipo.Objects;
                }
                else
                {
                    ViewBag.Message = "Ocurrio un error al buscar el dependiente";
                }
                return View(dependiente);
            }
        }

        [HttpPost]
        public ActionResult Form(ML.Dependiente dependiente)
        {
            //ADD
            if (dependiente.IdDependiente == 0)
            {
                ML.Result result = BL.Dependiente.Add(dependiente);
                if (result.Correct)
                {
                    ViewBag.Message = result.Message;
                }
                else
                {
                    ViewBag.Message = "Error: " + result.Message;
                }
            }
            //else
            {
                //UPDATE
                if (dependiente != null)
                {
                    ML.Result result = BL.Dependiente.Update(dependiente);
                    if (result.Correct)
                    {
                        ViewBag.Message = result.Message;
                    }
                    else
                    {
                        ViewBag.Message = "Error: " + result.Message;
                    }
                }
            }
            return PartialView("Modal");
        }

        public ActionResult Delete(ML.Dependiente dependiente)
        {
            if (dependiente != null)
            {
                ML.Result result = BL.Dependiente.Delete(dependiente);
                if (result.Correct)
                {
                    ViewBag.Message = result.Message;
                }
                else
                {
                    ViewBag.Message = "Error: " + result.Message;
                }
            }
            else
            {
                return Redirect("/Dependiente/GetAll");
            }
            return PartialView("Modal");
        }

    }
}

PL/Views/EmpleadoDependiente/Form.cshtml
@model ML.Dependiente
@{
    ViewData["Title"] = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <h2>Form</h2>
    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("Form", "EmpleadoDependiente", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <h3 class="text-center">Datos del empleado</h3>
                <div class="form-horizontal">
                    <div class="form-group">

                        <div class="col-md-3">

                            @Html.HiddenFor(model => model.IdDependiente)

                            @*@Html.TextBoxFor(model => model.IdUsuario, new { @class = "hidden form-control" })

                        @Html.ValidationMessageFor(model => model.IdUsuario)*@
                        </div>
                    </div>
                    <div class="container">
                        <div class="row">
                            <div class="col">                          

                                <div class="col mt-3">

                                    @Html.LabelFor(model => model.Nombre)
                                    
                                    <div class="input-group">
                                        
                                        <span class="input-group-text"><i class="bi bi-person"></i></span>
                                        @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @id = "txtNombre" })

                                    </div>

                                    @Html.ValidationMessageFor(model => model.Nombre)

                                </div>

                                <div class="col mt-3">

                                    @Html.LabelFor(model => model.ApellidoPaterno)

                                    <div class="input-group">

                                        <span class="input-group-text"><i class="bi bi-person"></i></span>
                                        @Html.TextBoxFor(model => model.ApellidoPaterno, new { @class = "form-control" })

                                    </div>

                                    @Html.ValidationMessageFor(model => model.ApellidoPaterno)

                                </div>

                                <div class="col mt-3">

                                    @Html.LabelFor(model => model.ApellidoMaterno)

                                    <div class="input-group">

                                        <span class="input-group-text"><i class="bi bi-person"></i></span>
                                        @Html.TextBoxFor(model => model.ApellidoMaterno, new { @class = "form-control" })

                                    </div>

                                    @Html.ValidationMessageFor(model => model.ApellidoMaterno)

                                </div>

                            </div>

                            <div class="col">

                                <div class="col mt-3">

                                    @Html.LabelFor(model => model.FechaNacimiento)

                                    <div class="input-group">

                                        <span class="input-group-text"><i class="bi bi-calendar"></i></span>
                                        @Html.TextBoxFor(model => model.FechaNacimiento, new { @class = "form-control", @id="txtFechaNacimiento" })

                                    </div>

                                    @Html.ValidationMessageFor(model => model.FechaNacimiento)

                                </div>

                                <div class="col mt-3">

                                    @Html.LabelFor(model => model.EstadoCivil)

                                    <div class="input-group">

                                        <span class="input-group-text"><i class="bi bi-envelope-at"></i></span>
                                        @Html.TextBoxFor(model => model.EstadoCivil, new { @class = "form-control" })

                                    </div>

                                    @Html.ValidationMessageFor(model => model.EstadoCivil)

                                </div>

                                <div class="col mt-3">
                                    @Html.LabelFor(model => model.Genero, htmlAttributes: new { @class = "control-label col-md-2" })
                                    @if (Model.Genero == '\0' || Model.Genero == null)
                                    {
                                        <div class="form-check">
                                            @Html.RadioButtonFor(model => model.Genero,'M',new  { @class="form-check-input", type="radio" } )
                                            <label class="form-check-label" for="flexRadioDefault1">Hombre</label>
                                        </div>
                                        <div class="form-check">
                                            @Html.RadioButtonFor(model => model.Genero,'F',new { @class="form-check-input", type="radio" }  )
                                            <label class="form-check-label" for="flexRadioDefault1">Mujer</label>
                                        </div>
                                    }
                                    else if (Model.Genero == 'M')
                                    {
                                        <div class="form-check">
                                            @Html.RadioButtonFor(model => model.Genero,'M',new  { @class="form-check-input", type="radio", @checked = "checked" } )
                                            <label class="form-check-label" for="flexRadioDefault1">Hombre</label>
                                        </div>
                                        <div class="form-check">
                                            @Html.RadioButtonFor(model => model.Genero,'F',new { @class="form-check-input", type="radio"  }  )
                                            <label class="form-check-label" for="flexRadioDefault1">Mujer</label>
                                        </div>
                                    }
                                    else if (Model.Genero == 'F')
                                    {
                                        <div class="form-check">
                                            @Html.RadioButtonFor(model => model.Genero,'M',new  { @class="form-check-input", type="radio" } )
                                            <label class="form-check-label" for="flexRadioDefault1">Hombre</label>
                                        </div>
                                        <div class="form-check">
                                            @Html.RadioButtonFor(model => model.Genero,'F',new { @class="form-check-input", type="radio", @checked = "checked" }  )
                                            <label class="form-check-label" for="flexRadioDefault1">Mujer</label>
                                        </div>
                                    }
                                    @Html.ValidationMessageFor(model => model.Genero)
                                </div>

                                <div class="col mt-3">

                                    @Html.LabelFor(model => model.Telefono)

                                    <div class="input-group">

                                        <span class="input-group-text"><i class="bi bi-person-vcard-fill"></i></span>
                                        @Html.TextBoxFor(model => model.Telefono, new { @class = "form-control" })

                                    </div>

                                    @Html.ValidationMessageFor(model => model.Telefono)

                                </div>

                            </div>

                            <div class="col">

                                <div class="col mt-3">

                                    @Html.LabelFor(model => model.Rfc)

                                    <div class="input-group">

                                        <span class="input-group-text"><i class="bi bi-calendar"></i></span>
                                        @Html.TextBoxFor(model => model.Rfc, new { @class = "form-control"})

                                    </div>

                                    @Html.ValidationMessageFor(model => model.Rfc)

                                </div>

                                <div class="col mt-3">

                                    @Html.LabelFor(model => model.Empleado)

                                    <div class="input-group">

                                        <span class="input-group-text"><i class="bi bi-person-badge"></i></span>
                                        @Html.DropDownListFor(model => model.Empleado.NumeroEmpleado, new SelectList(Model.Empleado.Empleados, "NumeroEmpleado", "Nombre"), "Seleccione un empleado", new { @class = "form-control" })

                                    </div>

                                    @Html.ValidationMessageFor(model => model.Empleado.NumeroEmpleado)

                                </div>

                                <div class="col mt-3">
                                    @Html.LabelFor(model => model.DependienteTipo)
                                    <div class="input-group">

                                        <span class="input-group-text"><i class="bi bi-person-rolodex"></i></span>
                                        @Html.DropDownListFor(model => model.DependienteTipo.IdDependienteTipo, new SelectList(Model.DependienteTipo.DependienteTipos, "IdDependienteTipo", "Nombre"), "Seleccione un tipo de dependiente", new { @class = "form-control" })

                                    </div>
                                    @Html.ValidationMessageFor(model => model.DependienteTipo.IdDependienteTipo)
                                </div>
                                
                            </div>                           
                        </div>
                    </div>

                    <div class="container">
                        <div class="row justify-content-md-center mt-5">
                            <div class="col col-lg-2">
                                <input type="submit" value="Guardar" class="btn btn-success" />

                                <a class="btn btn-danger " href="@Url.Action("GetAllDp", "EmpleadoDependiente",  new { NumeroEmpleado = Model.Empleado.NumeroEmpleado })"> Regresar</a>
                            </div>
                        </div>
                    </div>

                </div>
            }
        </div>
    </div>
</div>

@section Scripts{
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
    <script type="text/javascript">
        function readImage(imagen) {
            var fileName = imagen.value;
            var idxDot = fileName.lastIndexOf(".") + 1;
            var extFile = fileName.substr(idxDot, fileName.length).toLowerCase();

            if (extFile == "jpg" || extFile == "jpeg" || extFile == "png") {

                if (imagen.files && imagen.files[0]) {
                    var reader = new FileReader();
                    reader.onload = (e) => {
                        $("#ImagenPreview").attr("src", e.target.result);
                    };
                    reader.readAsDataURL(imagen.files[0]);
                }

            } else {

                alert("This is not an allowed file type. \nOnly jpg / jpeg and png files are allowed!.");

                $('#inputImage').val(null);

                $("#ImagenPreview").attr("src", "~/Image/sin usuario.jpg");

            }
        }

        $(function () {
            $("#txtFechaNacimiento").datepicker({
                dateFormat: 'dd/mm/yy',
                changeMonth: true,
                changeYear: true,
                yearRange: '-100:+0'
            });
        });

        $(function () {
            $("#txtFechaIngreso").datepicker({
                dateFormat: 'dd/mm/yy',
                changeMonth: true,
                changeYear: true,
                yearRange: '-100:+0'
            });
        });
    </script>
}

PL/Views/EmpleadoDependiente/GetAll.cshtml
@model ML.Empleado
@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h2>Lista de empleados</h2>
    <p>Aqui puedes seleccionar un empleado para ver su dependencia</p>
    <p>Para ver la dependencia de un empleado presione el boton Azul</p>
    <hr />

    @*@using (Html.BeginForm("GetAll", "EmpleadoDependiente", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="container mt-5">
            <div class="row">
                <h5>Buscar Empleado</h5>
                <div class="col-md-3">
                    <div class="form-group">

                        @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @placeholder = "Nombre" })

                    </div>
                </div>

                <div class="col-md-3">
                    <div class="container">
                        <div class="row justify-content-md-center">
                            <div class="col col-lg-2">
                                <input type="submit" value="Buscar" class="btn btn-warning" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }*@

    <div class="row mt-5">
        <table class="table table-responsive" id="tblEmpleado">
            <thead class="table-dark">
                <tr>
                    <th>
                        NumeroEmpleado
                    </th>
                    <th>
                        RFC
                    </th>
                    <th>
                        Nombre
                    </th>
                    <th>
                        Apellido Paterno
                    </th>
                    <th>
                        Apellido Materno
                    </th>
                    <th>
                        Email
                    </th>
                    <th>
                        Fecha de Nacimiento
                    </th>
                    <th>
                        NSS
                    </th>
                    <th>
                        Fecha de ingreso
                    </th>
                    <th>
                        Foto
                    </th>
                    <th>
                        Empresa
                    </th>
                    <th>
                        Dependencia
                    </th>
                </tr>
            </thead>
            <tbody class="table-info">
                @foreach (ML.Empleado empleado in Model.Empleados)
                {
                    <tr>
                        <td>
                            @empleado.NumeroEmpleado
                        </td>
                        <td>
                            @empleado.RFC
                        </td>
                        <td>
                            @empleado.Nombre
                        </td>
                        <td>
                            @empleado.ApellidoPaterno
                        </td>
                        <td>
                            @empleado.ApellidoMaterno
                        </td>
                        <td>
                            @empleado.Email
                        </td>
                        <td>
                            @empleado.FechaNacimiento
                        </td>
                        <td>
                            @empleado.NSS
                        </td>
                        <td>
                            @empleado.FechaIngreso
                        </td>
                        <td>
                            @if (empleado.Foto != null)
                            {
                                var imagenSRC = $"data:image;base64,{empleado.Foto}";
                                <img src='@imagenSRC' height='150px' width='150px'>
                            }
                            else
                            {
                                <img src="~/Image/sinlogo.jpg" height='150px' width='150px' />
                            }
                        </td>
                        @*<td class="hidden">
                    @empleado.Empresa.IdEmpresa
                    </td>*@
                        <td>
                            @empleado.Empresa.Nombre
                        </td>
                        <td class="text-center">
                            <a class="btn btn-primary" href="@Url.Action("GetAllDp", "EmpleadoDependiente", new { NumeroEmpleado = empleado.NumeroEmpleado })">Seleccionar</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@section Scripts
    {

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/dataTables.material.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap5.min.js"></script>

    <script>
        $(document).ready(function () {
            $('#tblEmpleado').DataTable({
                searching: false,
                "lengthMenu": [[5, 10, 15, 20, -1], [5, 10, 15, 20, "All"]],
                autoWidth: false,
                columnDefs: [
                    {
                        targets: ['_all'],
                        className: 'mdc-data-table__cell',
                    },
                ],
                language: {
                    url: "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json",
                },
            });
        });
    </script>

}

PL/Views/EmpleadoDependiente/GetAllDp.cshtml
@model ML.Dependiente
@{
    ViewData["Title"] = "GetAllDp";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    <h2>Lista de dependientes</h2>
    <p>Aqui puede ver, editar o agregar a un dependiente</p>
    <p>Para agregar a un dependiente presione el boton verde</p>
    <p>Para editar a un dependiente presione el boton azul</p>
    <p>Para eliminar a un dependiente presione el boton rojo</p>
    <p>Para buscar a un dependiente presione el boton amarillo</p>
    <hr />

    <div class="row">
        <div style="float:right">
            @Html.ActionLink("+", "Form", "Dependiente", htmlAttributes: new { @class = "btn btn-success" })
        </div>
    </div>

    @*@using (Html.BeginForm("GetAll", "Dependiente", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="container mt-5">
            <div class="row">
                <h5>Buscar Empleado</h5>
                <div class="col-md-3">
                    <div class="form-group">

                        @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @placeholder = "Nombre" })

                    </div>
                </div>

                <div class="col-md-3">
                    <div class="container">
                        <div class="row justify-content-md-center">
                            <div class="col col-lg-2">
                                <input type="submit" value="Buscar" class="btn btn-warning" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }*@

    <div class="row mt-5">
        <table class="table table-responsive" id="tblDependiente">
            <thead class="table-dark">
                <tr>
                    <th>
                        IdDependiente
                    </th>
                    <th>
                        Nombre Empleado
                    </th>
                    <th>
                        Nombre
                    </th>
                    <th>
                        Apellido Paterno
                    </th>
                    <th>
                        Apellido Materno
                    </th>
                    <th>
                        Fecha de Nacimiento
                    </th>
                    <th>
                        Estado Civil
                    </th>
                    <th>
                        Genero
                    </th>
                    <th>
                        Telefono
                    </th>
                    <th>
                        RFC
                    </th>
                    <th>
                        Tipo de dependiente
                    </th>
                    <th>
                        Editar
                    </th>
                    <th>
                        Eliminar
                    </th>
                </tr>
            </thead>
            <tbody class="table-info">
                @foreach (ML.Dependiente dependiente in Model.Dependientes)
                {
                    <tr>
                        <td>
                            @dependiente.IdDependiente
                        </td>
                        <td>
                            @dependiente.Empleado.Nombre @dependiente.Empleado.ApellidoPaterno @dependiente.Empleado.ApellidoMaterno
                        </td>
                        <td>
                            @dependiente.Nombre
                        </td>
                        <td>
                            @dependiente.ApellidoPaterno
                        </td>
                        <td>
                            @dependiente.ApellidoMaterno
                        </td>
                        <td>
                            @dependiente.FechaNacimiento
                        </td>
                        <td>
                            @dependiente.EstadoCivil
                        </td>
                        <td>
                            @dependiente.Genero
                        </td>
                        <td>
                            @dependiente.Telefono
                        </td>
                        <td>
                            @dependiente.Rfc
                        </td>
                        <td>
                            @dependiente.DependienteTipo.Nombre
                        </td>
                        <td class="text-center">
                            <a class="btn btn-primary bi-pencil-square" href="@Url.Action("Form", "EmpleadoDependiente", new { IdDependiente = dependiente.IdDependiente })"></a>
                        </td>
                        <td class="text-center">
                            <a class="btn btn-danger bi-trash" href="@Url.Action("Delete", "EmpleadoDependiente", new { IdDependiente = dependiente.IdDependiente })" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@section Scripts
    {

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/dataTables.material.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap5.min.js"></script>

    <script>
        $(document).ready(function () {
            $('#tblDependiente').DataTable({
                searching: false,
                "lengthMenu": [[5, 10, 15, 20, -1], [5, 10, 15, 20, "All"]],
                autoWidth: false,
                columnDefs: [
                    {
                        targets: ['_all'],
                        className: 'mdc-data-table__cell',
                    },
                ],
                language: {
                    url: "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json",
                },
            });
        });
    </script>

}

PL/Views/EmpleadoDependiente/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Regresar", "GetAllDp", "EmpleadoDependiente", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>